### PR TITLE
3 feature generate overall win loss

### PR DESCRIPTION
**Pull request by JD0517**
New menu (RL Stats Functions) and item (Create Overall...) with subitem (teams).

Allows users to create a section in the overall page which displays the wins and losses of all teams in the sheet names (seasons) input by the user.

If testing do it on a new sheet then delete it after.

### CODE REVIEW

**Comment by rzwoebkenberg** [comment]
Can we demo this again because it seems to look different than what is in the sheets right now. I definitely could have missed something regarding that, though

**Comment by JD0517** [comment]
The differences should only be color (which we can change if we want) and the orange and blue teams wins and losses are above all the teams now. I can probably move those back underneath tho, there was some reason I moved it but I can’t remember what it was.

**Comment by JD0517** [comment]
> Can we demo this again
Lets do that and close this out

**Review by rzwoebkenberg — APPROVED** [review]
LGTM

**Pull request merged**
